# Generated by Django 2.2 on 2020-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Folder', '0002_orderbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fa', 'Fantasy'), ('Bi', 'Biographies'), ('Sc', 'Sci-Fi'), ('Ho', 'Horror'), ('Ro', 'Romance')], max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
